### ISSUE TITLE
restore_No match found for backups with date

### ISSUE THREAD

**Issue by mycloudops** [valferon/postgres-manage-python#3]
I have mentioned proper date but It is still showing error "No match found for backups with date". 
Could you please solve the issue and give me solution.

**Comment by jonti09** [comment]
This is a little late for anyone trying to use this service, but there's bug which leads the user in wrong direction with the expected date format for the restore service.

For the time being disregard the "YYYY-MM-dd" format suggested in the usage guide, and use the "YYYYMMdd" format.
Notice the lack of "-" in the input.
